version: '3'

services:
  my_airflow_service:
    build:
      context: .
    container_name: my_airflow_container
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    image: my_airflow_image:latest
